Repository WildCodeSchool/purple-php-2109-project3-skillswap, pull requests merged in 2022-01, with the labels that each got.

#7 modify readme
  README.md
Labels: reviewed

#9 Us6 1
  assets/styles/_body.scss
  assets/styles/_home.scss
  assets/styles/_skillsResearch.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  migrations/Version20220103115651.php
  src/Controller/SkillsController.php
  src/DataFixtures/SkillsFixtures.php
  src/Entity/Skills.php
  src/Repository/SkillsRepository.php
  templates/_navbar.html.twig
  templates/home/index.html.twig
  templates/skills/research.html.twig
  templates/skills/show.html.twig
Labels: reviewed

#11 contact us mail create and send
  assets/styles/_contact.scss
  assets/styles/app.scss
  config/services.yaml
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  templates/_footer.html.twig
  templates/contact/index.html.twig
  templates/contact/send.html.twig
  templates/contact/valid.html.twig
Labels: reviewed

#13 Profil
  assets/images/fond_footer.png
  assets/images/fond_header.png
  assets/images/fond_header2.jpg
  assets/images/homeGif.gif
  assets/images/logo.png
  assets/images/logo2.png
  assets/styles/_profil.scss
  assets/styles/app.scss
  config/packages/security.yaml
  config/packages/translation.yaml
  config/services.yaml
  public/upload/avatars/avatar-29.png
  public/upload/avatars/defaultUserPicture.png
  src/Controller/HomeController.php
  src/Controller/RegistrationController.php
  src/Controller/SkillController.php
  src/Controller/SkillsController.php
  src/Controller/UserController.php
  src/DataFixtures/SkillsFixtures.php
  src/Entity/Skill.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Form/UserType.php
  src/Repository/SkillRepository.php
  src/Repository/UserRepository.php
  templates/_navbar.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/login/unverified.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  templates/users/_delete_form.html.twig
  templates/users/_form.html.twig
  templates/users/edit_profile.html.twig
  templates/users/profile.html.twig
Labels: reviewed, priority 3

#15 No s
  migrations/Version20220111160209.php
  src/Controller/SkillController.php
  src/DataFixtures/SkillFixtures.php
Labels: reviewed, priority 1

#17 Comment
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Controller/LoginController.php
  src/Controller/RegistrationController.php
  src/Controller/SkillController.php
  src/DataFixtures/SkillFixtures.php
  src/Entity/Contact.php
  src/Entity/Skill.php
  src/Entity/User.php
  src/Form/ContactType.php
  src/Form/RegistrationFormType.php
Labels: reviewed, priority 1

#14 skill selection when completing profil
  migrations/Version20220113160714.php
  src/Controller/RegistrationController.php
  src/Controller/SkillController.php
  src/Controller/UserController.php
  src/Entity/Skill.php
  src/Entity/User.php
  src/Form/UserSkillType.php
  src/Repository/SkillRepository.php
  templates/profil/_userSkillForm.html.twig
  templates/profil/index.html.twig
  templates/skills/research.html.twig
Labels: reviewed, priority 1

#18 Search user
  assets/styles/_swap.scss
  assets/styles/app.scss
  public/upload/avatars/bench.webp
  public/upload/avatars/homme_defaut.png
  src/Controller/SkillController.php
  src/Controller/SwapController.php
  src/Controller/UserController.php
  src/DataFixtures/SkillFixtures.php
  src/Entity/Skill.php
  src/Entity/User.php
  src/Form/UserSkillType.php
  src/Repository/SkillRepository.php
  templates/skills/research.html.twig
  templates/skills/show.html.twig
  templates/swap/research.html.twig
Labels: reviewed, priority 1

#19 Dispo or not
  src/Controller/SkillController.php
  src/Controller/UserController.php
  templates/users/profile.html.twig
Labels: reviewed

#22 Fix
  src/Controller/UserController.php
  templates/profil/index.html.twig
  templates/skills/research.html.twig
  templates/users/_userSkillForm.html.twig
  templates/users/profile.html.twig
Labels: reviewed

#23 correction readme
  README.md
Labels: reviewed

#16 Us12 comment profile
  migrations/Version20220114094552.php
  src/Controller/CommentController.php
  src/DataFixtures/SkillFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Comment.php
  src/Entity/User.php
  src/Form/CommentType.php
  src/Repository/CommentRepository.php
  templates/_navbar.html.twig
  templates/comment/index.html.twig
Labels: reviewed

#24 fix syntaxe twig fashError
  templates/registration/register.html.twig
Labels: reviewed

#26 creat role admin and first admin
  README.md
  config/packages/security.yaml
  src/Controller/UserController.php
  templates/users/profile.html.twig
Labels: reviewed, priority 1

#31 Nav admin
  assets/styles/_admin.scss
  templates/admin/_adminNav.html.twig
Labels: reviewed, priority 2

#28 Admin user
  src/Controller/AdminController.php
  templates/admin/dashboard.html.twig
  templates/admin/user_show.html.twig
  templates/admin/users.html.twig
Labels: reviewed, priority 1

#36 Us12 comment profile (Star rating)
  assets/styles/_comment.scss
  assets/styles/app.scss
  migrations/Version20220117101031.php
  src/Controller/CommentController.php
  src/Entity/Comment.php
  src/Entity/User.php
  src/Form/CommentType.php
  src/Repository/CommentRepository.php
  templates/comment/index.html.twig
Labels: reviewed

#34 limitation numbers char in descrption text
  src/Entity/User.php
Labels: reviewed

#32 css for view profil
  assets/styles/_profil.scss
  public/upload/avatars/avatar-29.png
  templates/users/profile.html.twig
Labels: reviewed

#30 Admin edit skill
  assets/styles/_admin.scss
  src/Controller/AdminController.php
  templates/admin/_delete_skill.html.twig
  templates/admin/skill_edit.html.twig
Labels: reviewed

#37 contactUs : auto-fill firstname and email when connected
  src/Controller/ContactController.php
  src/Form/ContactType.php
  templates/contact/index.html.twig
  templates/contact/send.html.twig
  templates/contact/valid.html.twig
Labels: reviewed

#40 add comment and moderation comment in profile
  assets/images/delete.jpg
  assets/styles/_profil.scss
  src/Controller/UserController.php
  templates/users/_delete_comment_form.html.twig
  templates/users/profile.html.twig
Labels: reviewed, priority 1

#41 fix on notation from registration
  src/Entity/User.php
Labels: reviewed

#42 modify home view
  assets/images/home.jpg
  assets/images/home.png
  assets/styles/_home.scss
  templates/_footer.html.twig
  templates/home/index.html.twig
Labels: reviewed

#38 delete profile fix
  src/Controller/UserController.php
  templates/users/_delete_form.html.twig
Labels: reviewed

#39 Us9 1 create swap
  migrations/Version20220118160050.php
  src/Controller/SwapController.php
  src/Entity/Swap.php
  src/Entity/User.php
  src/Form/SwapType.php
  src/Repository/SwapRepository.php
  templates/swap/index.html.twig
  templates/swapper/display.html.twig
Labels: reviewed

#43 Profile
  assets/styles/_nav-footer.scss
  assets/styles/_profil.scss
  assets/styles/variables.scss
  config/packages/twig.yaml
  src/Form/UserSkillType.php
  templates/users/profile.html.twig
Labels: reviewed

#44 add text in cgu page
  assets/styles/_cgu.scss
  assets/styles/app.scss
  templates/home/cgu.html.twig
Labels: reviewed

#47 Add a construct to the swap entity.
  src/Controller/SwapController.php
  src/Entity/Swap.php
Labels: reviewed

#48 DRY code for Skill accordion
  src/DataFixtures/SkillFixtures.php
  src/Entity/Skill.php
  src/Form/SkillType.php
  templates/skills/research.html.twig
Labels: reviewed

#49 swapper filter
  templates/swap/research.html.twig
Labels: reviewed

#51 css on swapper display
  assets/styles/_swap.scss
  src/Entity/User.php
  templates/swapper/display.html.twig
Labels: reviewed

#50 Us9 3 message entity
  assets/styles/_swapDashboard.scss
  assets/styles/app.scss
  migrations/Version20220125153241.php
  src/Controller/SwapDashboardController.php
  src/Entity/Discussion.php
  src/Entity/Swap.php
  src/Form/DiscussionType.php
  src/Repository/DiscussionRepository.php
  src/Repository/SwapRepository.php
  templates/swap_dashboard/index.html.twig
Labels: reviewed

#53 add comment and delete comment from admin
  assets/styles/_admin.scss
  src/Controller/AdminController.php
  src/Entity/User.php
  templates/admin/_delete_comment_form.html.twig
  templates/admin/dashboard.html.twig
  templates/admin/user_show.html.twig
  templates/admin/users.html.twig
Labels: reviewed

#54 Admin user role
  src/Controller/AdminController.php
  templates/admin/user_show.html.twig
Labels: reviewed

#55 Sort users by their rating.
  templates/swap/research.html.twig
Labels: reviewed

#57 Us11 end of swap
  assets/styles/_body.scss
  assets/styles/_swapDashboard.scss
  assets/styles/app.scss
  src/Controller/SwapDashboardController.php
  templates/swap_dashboard/index.html.twig
Labels: reviewed

#56 Admin delete user
  src/Controller/AdminController.php
  templates/admin/_delete_user_form.html.twig
  templates/admin/user_show.html.twig
Labels: reviewed

#58 correctif home page css
  assets/styles/_body.scss
  assets/styles/_home.scss
  templates/home/index.html.twig
Labels: reviewed

#52 CSS for connexion
  assets/images/bin.png
  assets/images/delete.jpg
  assets/styles/_login.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/login/index.html.twig
Labels: Ask for 2 review

#59 css in dashboard admin
  assets/styles/_admin.scss
  templates/admin/dashboard.html.twig
Labels: reviewed

#60 css in users admin and user admin
  assets/styles/_admin.scss
  templates/admin/user_show.html.twig
  templates/admin/users.html.twig
Labels: reviewed

#64 CSS on swapper display and star rating
  assets/images/star15bgless.png
  assets/images/star1bgless.png
  assets/images/star25bgless.png
  assets/images/star2bgless.png
  assets/images/star35bgless.png
  assets/images/star3bgless.png
  assets/images/star45bgless.png
  assets/images/star4bgless.png
  assets/images/star5bgless.png
  assets/styles/_swap.scss
  templates/swap/research.html.twig
  templates/swapper/display.html.twig
Labels: reviewed

#65 Profile grid
  assets/styles/_profil.scss
  assets/styles/variables.scss
  templates/users/_delete_comment_form.html.twig
  templates/users/_userSkillForm.html.twig
  templates/users/profile.html.twig
Labels: reviewed

#66 Titles legal mentions
  assets/styles/_cgu.scss
  templates/home/cgu.html.twig
  templates/registration/register.html.twig
Labels: reviewed, Ask for 2 review

#67 Modification of the list of skills
  src/DataFixtures/SkillFixtures.php
Labels: reviewed, Ask for 2 review

#71 css in edit profile
  assets/styles/_profil.scss
  src/Form/UserType.php
  templates/users/_delete_form.html.twig
  templates/users/_form.html.twig
  templates/users/edit_profile.html.twig
Labels: reviewed

#72 border orange
  assets/styles/_body.scss
  assets/styles/_login.scss
  assets/styles/_skillsResearch.scss
Labels: reviewed

#69 Admin next
  assets/styles/_admin.scss
  templates/admin/_adminNav.html.twig
  templates/admin/_delete_comment_form.html.twig
  templates/admin/_delete_skill.html.twig
  templates/admin/_formSkill.html.twig
  templates/admin/skill.html.twig
  templates/admin/skill_edit.html.twig
  templates/admin/user_show.html.twig
  templates/admin/users.html.twig
Labels: reviewed

#70 Us10 dashboard
  assets/styles/_dashboard.scss
  assets/styles/app.scss
  src/Controller/DashboardController.php
  src/Entity/User.php
  templates/_navbar.html.twig
  templates/contact/index.html.twig
  templates/dashboard/index.html.twig
Labels: To validate after the previous one

#68 Delete user fixtures
  src/DataFixtures/UserFixtures.php
Labels: reviewed

#74 W3 c
  assets/styles/_home.scss
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: reviewed

#75 Dashboard
  assets/styles/_dashboard.scss
  src/Controller/SwapDashboardController.php
  templates/dashboard/index.html.twig
  templates/swap_dashboard/index.html.twig
Labels: reviewed

#76 register css modifications
  assets/styles/_register.scss
  assets/styles/app.scss
  src/Controller/RegistrationController.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: reviewed

#77 Css contact us
  assets/styles/_contact.scss
  templates/contact/index.html.twig
Labels: reviewed

#78 correction of messages index
  templates/comment/index.html.twig
  templates/contact/index.html.twig
  templates/swap/index.html.twig
Labels: reviewed

#79 fix for sleep
  src/Entity/Comment.php
  src/Entity/Discussion.php
  src/Entity/Skill.php
  src/Entity/Swap.php
  src/Entity/User.php
Labels: reviewed

#62 Notification
  src/Controller/SwapController.php
  src/Controller/SwapDashboardController.php
  src/Service/SortUserAskerHelper.php
  templates/swap/send.html.twig
  templates/swap_dashboard/send.html.twig
Labels: reviewed

#82 Fix the columns names and the user names displayed.
  templates/dashboard/index.html.twig
Labels: reviewed

#84 Fix bracket that made a margin spread in the global css.
  assets/styles/_contact.scss
Labels: reviewed

#85 Add comments to methods
  src/Controller/AdminController.php
  src/Controller/DashboardController.php
  src/Controller/SkillController.php
  src/Controller/SwapController.php
  src/Controller/SwapDashboardController.php
  src/Controller/UserController.php
  src/Service/SortUserAskerHelper.php
Labels: reviewed
